/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactivefilereadingjava;

import io.reactivex.rxjava3.annotations.NonNull;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.core.Scheduler;
import io.reactivex.rxjava3.schedulers.Schedulers;

public class ReadStream {

    public static Flowable<String> file_contents_observable(FileParser fileParser, @NonNull Scheduler fileParserScheduler, @NonNull Scheduler downstreamScheduler) {

        //Use FileParser methods to implement this
        //It should only read file contents if the modified date changes
        //and no tests should need to be modified to get this implementation working.

        //Stub method so that tests will compile (and fail).
        return Flowable.just("");

    }

    public static void main(String[] args) throws InterruptedException {


        String fileName = "/dev/shm/myinput.txt";
        FileParser fileParser = new FileParser(fileName);

        file_contents_observable(fileParser, Schedulers.io(), Schedulers.computation()).subscribe(System.out::println);

        while(true) {
            Thread.sleep(10000);
        }
    }
}

